import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import javax.swing.JOptionPane;
import javax.swing.Timer;

/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author tengku
 */
public class Frame extends javax.swing.JFrame {
    
    private static Timer timer; 
    String def = "00";
    int jam, mnt, dtk;    
    Model model = new Model();
    boolean isTimerOn;
    String ip = "192.168.4.1";
    cekKoneksi cek;
    /**
     * Creates new form NewJFrame1
     */
    public Frame() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        ttd3 = new javax.swing.JLabel();
        ttd4 = new javax.swing.JLabel();
        display_menit2 = new javax.swing.JLabel();
        ttd5 = new javax.swing.JLabel();
        addwaktu2 = new javax.swing.JButton();
        display_jam2 = new javax.swing.JLabel();
        display_detik2 = new javax.swing.JLabel();
        ttd6 = new javax.swing.JLabel();
        display_menit3 = new javax.swing.JLabel();
        ttd7 = new javax.swing.JLabel();
        tgtBtn = new javax.swing.JToggleButton();
        addwaktu3 = new javax.swing.JButton();
        btn_simpan = new javax.swing.JButton();
        display_jam3 = new javax.swing.JLabel();
        display_jam = new javax.swing.JLabel();
        display_detik3 = new javax.swing.JLabel();
        display_detik = new javax.swing.JLabel();
        rmwaktu2 = new javax.swing.JButton();
        ttd = new javax.swing.JLabel();
        rmwaktu3 = new javax.swing.JButton();
        display_menit = new javax.swing.JLabel();
        rmwaktu1 = new javax.swing.JButton();
        ttd1 = new javax.swing.JLabel();
        check_koneksi = new javax.swing.JButton();
        addwaktu1 = new javax.swing.JButton();
        display_jam1 = new javax.swing.JLabel();
        display_detik1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        btn_stop = new javax.swing.JButton();
        btn_start = new javax.swing.JButton();
        input_jam = new javax.swing.JSpinner();
        input_mnt = new javax.swing.JSpinner();
        input_dtk = new javax.swing.JSpinner();
        jLabel1 = new javax.swing.JLabel();
        ttd2 = new javax.swing.JLabel();
        display_menit1 = new javax.swing.JLabel();
        statusListrik = new javax.swing.JLabel();
        filler1 = new javax.swing.Box.Filler(new java.awt.Dimension(2, 0), new java.awt.Dimension(2, 0), new java.awt.Dimension(2, 32767));
        filler2 = new javax.swing.Box.Filler(new java.awt.Dimension(0, 3), new java.awt.Dimension(0, 3), new java.awt.Dimension(32767, 3));
        reset = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(102, 153, 255));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        ttd3.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        ttd3.setText(":");
        jPanel1.add(ttd3, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 150, -1, -1));

        ttd4.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        ttd4.setText(":");
        jPanel1.add(ttd4, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 180, -1, -1));

        display_menit2.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        display_menit2.setText("00");
        jPanel1.add(display_menit2, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 180, -1, -1));

        ttd5.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        ttd5.setText(":");
        jPanel1.add(ttd5, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 180, -1, -1));

        addwaktu2.setText("+");
        addwaktu2.setBorder(null);
        addwaktu2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addwaktu2ActionPerformed(evt);
            }
        });
        jPanel1.add(addwaktu2, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 180, 38, 23));

        display_jam2.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        display_jam2.setText("00");
        jPanel1.add(display_jam2, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 180, -1, -1));

        display_detik2.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        display_detik2.setText("00");
        jPanel1.add(display_detik2, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 180, -1, -1));

        ttd6.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        ttd6.setText(":");
        jPanel1.add(ttd6, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 210, -1, -1));

        display_menit3.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        display_menit3.setText("00");
        jPanel1.add(display_menit3, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 210, -1, -1));

        ttd7.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        ttd7.setText(":");
        jPanel1.add(ttd7, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 210, -1, -1));

        tgtBtn.setText("OFF");
        tgtBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tgtBtnActionPerformed(evt);
            }
        });
        jPanel1.add(tgtBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 250, 69, -1));

        addwaktu3.setText("+");
        addwaktu3.setBorder(null);
        addwaktu3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addwaktu3ActionPerformed(evt);
            }
        });
        jPanel1.add(addwaktu3, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 210, 38, 23));

        btn_simpan.setText("Simpan");
        btn_simpan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_simpanActionPerformed(evt);
            }
        });
        jPanel1.add(btn_simpan, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 250, 71, -1));

        display_jam3.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        display_jam3.setText("00");
        jPanel1.add(display_jam3, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 210, -1, -1));

        display_jam.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        display_jam.setText("00");
        jPanel1.add(display_jam, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 50, -1, -1));

        display_detik3.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        display_detik3.setText("00");
        jPanel1.add(display_detik3, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 210, -1, -1));

        display_detik.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        display_detik.setText("00");
        jPanel1.add(display_detik, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 50, -1, -1));

        rmwaktu2.setText("-");
        rmwaktu2.setBorder(null);
        rmwaktu2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rmwaktu2ActionPerformed(evt);
            }
        });
        jPanel1.add(rmwaktu2, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 180, 38, 23));

        ttd.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        ttd.setText(":");
        jPanel1.add(ttd, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 50, -1, -1));

        rmwaktu3.setText("-");
        rmwaktu3.setBorder(null);
        rmwaktu3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rmwaktu3ActionPerformed(evt);
            }
        });
        jPanel1.add(rmwaktu3, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 210, 38, 23));

        display_menit.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        display_menit.setText("00");
        jPanel1.add(display_menit, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 50, -1, -1));

        rmwaktu1.setText("-");
        rmwaktu1.setBorder(null);
        rmwaktu1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rmwaktu1ActionPerformed(evt);
            }
        });
        jPanel1.add(rmwaktu1, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 150, 38, 23));

        ttd1.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        ttd1.setText(":");
        jPanel1.add(ttd1, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 50, -1, -1));

        check_koneksi.setText("Cek Status");
        check_koneksi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                check_koneksiActionPerformed(evt);
            }
        });
        jPanel1.add(check_koneksi, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 180, -1, -1));

        addwaktu1.setText("+");
        addwaktu1.setBorder(null);
        addwaktu1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addwaktu1ActionPerformed(evt);
            }
        });
        jPanel1.add(addwaktu1, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 150, 38, 23));

        display_jam1.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        display_jam1.setText("00");
        jPanel1.add(display_jam1, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 150, -1, -1));

        display_detik1.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        display_detik1.setText("00");
        jPanel1.add(display_detik1, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 150, -1, -1));

        jLabel2.setText("Menit");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 120, -1, -1));

        jLabel3.setText("Jam");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 120, -1, -1));

        btn_stop.setText("Stop");
        btn_stop.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_stopActionPerformed(evt);
            }
        });
        jPanel1.add(btn_stop, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 290, 70, -1));

        btn_start.setText("Start");
        btn_start.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_startActionPerformed(evt);
            }
        });
        jPanel1.add(btn_start, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 290, 69, -1));

        input_jam.setModel(new javax.swing.SpinnerNumberModel(0, 0, 23, 1));
        jPanel1.add(input_jam, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 90, 53, -1));

        input_mnt.setModel(new javax.swing.SpinnerNumberModel(0, 0, 59, 1));
        jPanel1.add(input_mnt, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 90, 51, -1));

        input_dtk.setModel(new javax.swing.SpinnerNumberModel(0, 0, 59, 1));
        jPanel1.add(input_dtk, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 90, 47, -1));

        jLabel1.setText("Detik");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 120, -1, -1));

        ttd2.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        ttd2.setText(":");
        jPanel1.add(ttd2, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 150, -1, -1));

        display_menit1.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        display_menit1.setText("00");
        jPanel1.add(display_menit1, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 150, -1, -1));

        statusListrik.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        statusListrik.setText("Listrik Menyala");
        jPanel1.add(statusListrik, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 170, -1, -1));
        jPanel1.add(filler1, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 160, 80, -1));
        jPanel1.add(filler2, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 330, -1, 50));

        reset.setText("Reset");
        reset.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                resetActionPerformed(evt);
            }
        });
        jPanel1.add(reset, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 270, -1, -1));

        getContentPane().add(jPanel1, java.awt.BorderLayout.CENTER);

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btn_startActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_startActionPerformed
        if (!display_detik.getText().equals("00") || !display_menit.getText().equals("00") || !display_jam.getText().equals("00")) {
            int interval = 1000;
            timer = new Timer(interval, new ActionListener() {
                @Override
                public void actionPerformed(ActionEvent e) {
                    int detik = Integer.parseInt(display_detik.getText());
                    int menit = Integer.parseInt(display_menit.getText());
                    int jam = Integer.parseInt(display_jam.getText());

                    if (detik > 0 || menit > 0 || jam > 0) {
                        if (detik == 0) {
                            if (menit > 0) {
                                menit--;
                                detik = 59;
                            } else if (jam > 0) {
                                jam--;
                                menit = 59;
                                detik = 59;
                            }
                        } else {
                            detik--;
                        }

                        display_detik.setText(String.format("%02d", detik));
                        display_menit.setText(String.format("%02d", menit));
                        display_jam.setText(String.format("%02d", jam));
                    } else {
                        isTimerOn = false;
                        tgtBtn.setSelected(true);
                        tgtBtn.setText("OFF");
                        statusListrik.setText("Listrik Mati");
                        timer.stop();
                        new Koneksi("http://" + ip+ "/led1off");
                        JOptionPane.showMessageDialog(null, "Waktu Habis!");
                    }
                }
            });
            isTimerOn = true;
            tgtBtn.setSelected(false);
            tgtBtn.setText("ON");
            statusListrik.setText("Listrik Menyala");
            timer.start();
            new Koneksi("http://" + ip+ "/led1on");
        } else {
            JOptionPane.showMessageDialog(null, "Waktu belum dimasukkan.");

        }
    }//GEN-LAST:event_btn_startActionPerformed

    private void btn_stopActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_stopActionPerformed
        if(isTimerOn == true){
            timer.stop();
            isTimerOn = false;// TODO add your handling code here:
        }else{
            JOptionPane.showMessageDialog(null, "Waktu Tidak Berjalan!");
        }
    }//GEN-LAST:event_btn_stopActionPerformed

    private void addwaktu1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addwaktu1ActionPerformed
        //memasukan waktu ke display utama
        if(isTimerOn == true){
            JOptionPane.showMessageDialog(null, "Waktu Sedang Berjalan!");
        }else{
            display_detik.setText(display_detik1.getText());
            display_menit.setText(display_menit1.getText());
            display_jam.setText(display_jam1.getText());
        }
    }//GEN-LAST:event_addwaktu1ActionPerformed

    private void check_koneksiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_check_koneksiActionPerformed
        cek = new cekKoneksi("http://"+ ip + "/status");
        if(cek.led1Status == 0){
            JOptionPane.showMessageDialog(null, "Terhubung & Listrik Mati!");
        }else{
            JOptionPane.showMessageDialog(null, "Terhubung & Listrik Menyala!");
        }
        
    }//GEN-LAST:event_check_koneksiActionPerformed

    private void rmwaktu1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rmwaktu1ActionPerformed
        //hapus waktu tersimpan
        display_detik1.setText(def);
        display_menit1.setText(def);
        display_jam1.setText(def);
    }//GEN-LAST:event_rmwaktu1ActionPerformed

    private void rmwaktu3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rmwaktu3ActionPerformed
        //hapus waktu tersimpan
        display_detik3.setText(def);
        display_menit3.setText(def);
        display_jam3.setText(def);
    }//GEN-LAST:event_rmwaktu3ActionPerformed

    private void rmwaktu2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rmwaktu2ActionPerformed
        //hapus waktu tersimpan
        display_detik2.setText(def);
        display_menit2.setText(def);
        display_jam2.setText(def);
    }//GEN-LAST:event_rmwaktu2ActionPerformed

    private void btn_simpanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_simpanActionPerformed
        model.setJam((int) input_jam.getValue());
        model.setMenit((int) input_mnt.getValue());
        model.setDetik((int) input_dtk.getValue());
        dtk = model.getDetik();
        mnt = model.getMenit();
        jam = model.getJam();

        if (display_detik1.getText().equals(def) && display_menit1.getText().equals(def) && display_jam1.getText().equals(def)) {
            display_detik1.setText(String.format("%02d", dtk));
            display_menit1.setText(String.format("%02d", mnt));
            display_jam1.setText(String.format("%02d", jam));
        } else if (display_detik2.getText().equals(def) && display_menit2.getText().equals(def) && display_jam2.getText().equals(def)) {
            display_detik2.setText(String.format("%02d", dtk));
            display_menit2.setText(String.format("%02d", mnt));
            display_jam2.setText(String.format("%02d", jam));
        } else if (display_detik3.getText().equals(def) && display_menit3.getText().equals(def) && display_jam3.getText().equals(def)) {
            display_detik3.setText(String.format("%02d", dtk));
            display_menit3.setText(String.format("%02d", mnt));
            display_jam3.setText(String.format("%02d", jam));
        }else{
            JOptionPane.showMessageDialog(null, "Hapus Waktu Tersimpan!");
        }

        // TODO add your handling code here:
    }//GEN-LAST:event_btn_simpanActionPerformed

    private void addwaktu3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addwaktu3ActionPerformed
        if(isTimerOn == true){
            JOptionPane.showMessageDialog(null, "Waktu Sedang Berjalan!");
        }else{
            display_detik.setText(display_detik1.getText());
            display_menit.setText(display_menit1.getText());
            display_jam.setText(display_jam1.getText());
        }
        // TODO add your handling code here:
    }//GEN-LAST:event_addwaktu3ActionPerformed

    private void tgtBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tgtBtnActionPerformed
        // TODO add your handling code here:
        if(tgtBtn.isSelected()){
            if(isTimerOn == true){
                timer.stop();
            }
            tgtBtn.setText("OFF");
            statusListrik.setText("Listrik Mati");
            new Koneksi("http://" + ip+ "/led1off");
            JOptionPane.showMessageDialog(null, "Listrik Mati");
        }else{
            tgtBtn.setText("ON");
            statusListrik.setText("Listrik Menyala");
            new Koneksi("http://" + ip+ "/led1on");
            JOptionPane.showMessageDialog(null, "Listrik Menyala");
        }
    }//GEN-LAST:event_tgtBtnActionPerformed

    private void addwaktu2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addwaktu2ActionPerformed
        if(isTimerOn == true){
            JOptionPane.showMessageDialog(null, "Waktu Sedang Berjalan!");
        }else{
            display_detik.setText(display_detik1.getText());
            display_menit.setText(display_menit1.getText());
            display_jam.setText(display_jam1.getText());
        }
        // TODO add your handling code here:
    }//GEN-LAST:event_addwaktu2ActionPerformed

    private void resetActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_resetActionPerformed
        // TODO add your handling code here:
        display_jam.setText("00");
        display_menit.setText("00");
        display_detik.setText("00");
    }//GEN-LAST:event_resetActionPerformed
    public void status(){
        cek = new cekKoneksi("http://"+ ip + "/status");
        if(cek.led1Status == 0){
            tgtBtn.setSelected(true);
            statusListrik.setText("Listrik Mati");
            tgtBtn.setText("OFF");
        }else{
            tgtBtn.setSelected(false);
            statusListrik.setText("Listrik Menyala");
            tgtBtn.setText("ON");
        }
    }
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Frame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Frame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Frame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Frame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                Frame frame = new Frame();
                frame.setVisible(true);
                frame.status();
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton addwaktu1;
    private javax.swing.JButton addwaktu2;
    private javax.swing.JButton addwaktu3;
    private javax.swing.JButton btn_simpan;
    private javax.swing.JButton btn_start;
    private javax.swing.JButton btn_stop;
    private javax.swing.JButton check_koneksi;
    private javax.swing.JLabel display_detik;
    private javax.swing.JLabel display_detik1;
    private javax.swing.JLabel display_detik2;
    private javax.swing.JLabel display_detik3;
    private javax.swing.JLabel display_jam;
    private javax.swing.JLabel display_jam1;
    private javax.swing.JLabel display_jam2;
    private javax.swing.JLabel display_jam3;
    private javax.swing.JLabel display_menit;
    private javax.swing.JLabel display_menit1;
    private javax.swing.JLabel display_menit2;
    private javax.swing.JLabel display_menit3;
    private javax.swing.Box.Filler filler1;
    private javax.swing.Box.Filler filler2;
    private javax.swing.JSpinner input_dtk;
    private javax.swing.JSpinner input_jam;
    private javax.swing.JSpinner input_mnt;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JButton reset;
    private javax.swing.JButton rmwaktu1;
    private javax.swing.JButton rmwaktu2;
    private javax.swing.JButton rmwaktu3;
    private javax.swing.JLabel statusListrik;
    private javax.swing.JToggleButton tgtBtn;
    private javax.swing.JLabel ttd;
    private javax.swing.JLabel ttd1;
    private javax.swing.JLabel ttd2;
    private javax.swing.JLabel ttd3;
    private javax.swing.JLabel ttd4;
    private javax.swing.JLabel ttd5;
    private javax.swing.JLabel ttd6;
    private javax.swing.JLabel ttd7;
    // End of variables declaration//GEN-END:variables
}
